# 모듈

- 미리 만들어진 파이썬 소스파일(라이브러리)
  - 파이썬은 모듈을 만들기 위한 추가적인 과정은 요구하지 않음
  - 파이썬 소스파일은 모듈이 될 수 있음
    - 다른 파이썬 소스파일에서 가져다 사용할 수 있다
  - 모듈은 재사용성을 위해서 나온 개념
- 쥬피터 노트북은 모듈이 될 수 없다
  - `ipynb` 파일은 모듈이 될 수 없다
  - 모듈은 확장자가 `py`인 파이썬 소스파일만 가능

## 패키지

- 여러 개의 모듈(파일)을 하나로 묶어서 패키지라고 함
- 파이썬 패키지를 폴더로 관리
  - 같은 폴더에 있으면 같은 패키지
  - 폴더의 이름이 패키지의 이름이 됨
- 파이썬 버전에 따라서 폴더를 패키지로 인식 여부가 다름
  - 그런 경우 해당 폴더에 `__init__.py` 파일이 있으면 패키지로 인식하게 됨
  - 버전과 상관없이 패키지로 인식하려면 파일을 만들어 두면 됨
  - 파일의 내용은 없어도 됨

## 여러가지 형태의 import

### 모듈의 이름이 너무 긴 경우

``` python
# as를 이용해서 별칭을 설정
# 별칭을 통해서 모듈을 참조
import my_first_module as lib
```

### from을 이용한 정의

```python
# from을 이용해서 모듈 내에서 임포트 하고자 하는 내용을 정확히 지정
from my_first_module import my_function
```

```python
# 패키지인 경우에는 패키지 내의 특정 모듈을 선택
from modules import my_area
```

```python
from modules import my_area as my
```

```python
# 패키지 내의 특정 모듈의 특정 내용을 정확히 지정
from modules.my_area import PI
```

```python
# *(와일드카드/all)
# 모듈내의 모든 내용을 전부 가져올 수도 있습니다. 
from modules.my_area import *
```

## 파이썬 소스 파일의 실행

- 파이썬 인터프리터는 아래의 두 경우를 구분
  1. 파이썬 소스 파일을 직접 실행
  2. 모듈로써 임포트 되어서 실행되는 경우

# 예외처리

- 코드를 작성하면서 발생할 수 있는 예외(에러, 경고, ...)에 대해서 처리할 수 있는 방법 2가지
  1. LBYL(Look Before You Leap)
     - **도약하기 전에 확인해라**
     - 코드를 실행하기 전에 예외가 발생하지 않도록 미리 검증하고 실행을 하자
     - 즉, 발생할 수 있는 모든 예외적인 상황들에 대해서 미리 예측하고, 미연에 방지
     - 현실적으로는 불가능
  2. EAFP(it's Easier Ask Forgiveness than Permission)
     - **허락보다 용서가 쉽다**
     - 일단 코드를 실행하고, 예외가 발생하면 그때 처리

## EAFP 방식의 예외처리

```python
def convert(strs):
  # 예외가 발생할 것 같은 코드를 try 블록으로 넣어줌
  # try 블록내의 코드를 모니터링(인터프리터가)
  try:
    return int(strs)
  except: # try 블록내의 코드에서 예외가 발생하면 except 블록으로 예외가 넘어오게 됨 
    # 발생한 예외를 어떻게 처리 할 것인가?
    # 예외가 발생하면 함수를 종료 하도록 만든 것 뿐
    return False
```

```python
convert('')
```

```
False
```

어느 한 가지 방법만을 이용하지는 않음

- try, except 만으로 모든 예외가 처리될 순 없다

### 다양한 형태의 예외처리 방법

#### 특정 예외만 처리하는 경우

```python
def convert(strs):
  try:
    return int(strs)
  except ValueError:
    return False

convert([])
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-54ed4199855c> in <module>()
----> 1 convert([])

<ipython-input-7-0418bc43ec0d> in convert(strs)
      1 def convert(strs):
      2   try:
----> 3     return int(strs)
      4   except ValueError:
      5     return False

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

`elif` 구문처럼 여러 개의 예외를 처리할 수 있음

```python
def convert(strs):
  try:
    return int(strs)
  except ValueError:
    print('ValueError')
  except TypeError:
    print('TypeError')
```

```python
convert('a')
```

```
ValueError
```

```python
convert([])
```

```
TypeError
```

예외별로 정확한 예외 메세지를 확인

```python
def convert(strs):
  try:
    return int(strs)
  except ValueError as e:
    print(e)
  except TypeError as e:
    print(e)
```

```python
convert('a')
```

```
invalid literal for int() with base 10: 'a'
```

```python
convert([])
```

```
int() argument must be a string, a bytes-like object or a number, not 'list'
```

여러 개의 예외를 하나로 묶어서 처리

```python
ef convert(strs):
  try:
    return int(strs)
  except (ValueError, TypeError) as e:
    print(e)
```

```python
convert('a')
```

```
invalid literal for int() with base 10: 'a'
```

```python
convert([])
```

```
int() argument must be a string, a bytes-like object or a number, not 'list'
```

- 파이썬은 예외도 객체
  - 파이썬의 모든 예외 클래스들은 전부 `Exception` 클래스를 상속 받아서 정의됨
  - `is-a` 속성에 따라서, 모든 예외는 `Exception`이라고 할 수 있다

- object 클래스
  - 모든 클래스의 `최상위 클래스`
  - 클래스를 정의할 때, 상속을 하지 않아도 기본적으로 `object` 클래스를 상속해서 정의
    - 굳이 상속을 정의하지 않아도 생략가능한 형태로, 항상 상속이 된다

```python
def convert(strs):
  try:
    return int(strs)

  # 주의!
  # 가장 큰 범위의 예외 클래스가 먼저 오지 않도록 해야 함
  except Exception as e:
    print('Unkown Exception', e)
  except ValueError as e:
    print('ValueError', e)
```

```python
# 이렇게 되면 ValueError는 절대 처리되지 않음
convert('a')
```

```
Unkown Exception invalid literal for int() with base 10: 'a'
```

#### 확장된 형태

- else, finally

```python
def convert(strs):
  try:
    print( int(strs) )
  except ValueError as e:
    print('ValueError', e)
  except Exception as e:
    print('Unkown Exception', e)
  else:
    print('예외가 발생하지 않으면 실행')
  finally:
    print('예외 유무와 상관없이 마지막에 항상 무조건 실행')
```

```python
convert(10)
```

```
10
예외가 발생하지 않으면 실행
예외 유무와 상관없이 마지막에 항상 무조건 실행
```

```python
convert('a')
```

```
ValueError invalid literal for int() with base 10: 'a'
예외 유무와 상관없이 마지막에 항상 무조건 실행
```

### 예외를 응용하는 경우

- 파이썬은 `EOF`도 예외로 처리함
  - `EOL`(End Of Line) => 라인의 끝(\n)
  - `EOF`(End Of File)
    - 파일의 가장 마지막에 들어가는 문자
    - 입력이 끝을 표현하는 경우
- 파이썬은 EOF를 처리하지 못함
  - 입력의 끝을 알 수 없음
  - windows : ctrl + z
  - linux, max : ctrl + d

### 처리되지 않은 예외

- 모든 예외를 전부 처리할 수 없음
- 예외도 여러 종류가 있다
  - 에러도 예외의 한 종류
  - 경고, 인터럽트 등 여러 종류의 예외 존재
  - 에러는 여러가지 예외들 중에서 프로그램 실행에 영향을 줄 만큼 심각한 오류
- 에러의 종류
  1. 컴파일 에러
     - 파이썬은 컴파일 과정이 없고 인터프리터 방식으로 동작
     - 그래서 파이썬에서는 컴파일이 아닌 인터프리트 과정에서 발생하는 에러
     - 문법적인 오류 등은 이 과정에서 발생
     - 예외처리가 되지 않음
  2.  런타인 에러
     - 프로그램을 실행 중(프로세스)인 상태에서 발생하는 에러
     - 번역은 끝난 상태(문법적인 오류는 없는 상태)에서 실행하는 도중에 문제가 발생하는 경우